development:
  adapter: sqlite3
  database: db/asagao_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: asagao_test
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8

production:
  adapter: mysql2
  database: asagao_production
  username: root
  password: 
  encoding: utf8